apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-api
  template:
    metadata:
      labels:
        app: expense-tracker-api
    spec:
      containers:
        - name: expense-tracker-api
          image: expense_tracker_api:latest
          ports:
            - containerPort: 8000
