apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-api-service
spec:
  selector:
    app: expense-tracker-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
